# Generated by Django 3.1.1 on 2021-11-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feggystreats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
